name: portable-shulkers
version: '${version}'
main: xyz.terriblefriends.portableshulkers.PortableShulkers
api-version: '1.20'
dependencies:
  server:
    CombatLogX:
      required: false
      join-classpath: true